# Generated by Django 2.2.15 on 2020-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200824_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGngfmh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgfhgfhgf', models.BigIntegerField()),
            ],
        ),
    ]
